openapi: 3.0.3
info:
  title: WASAPhoto API
  description: "Web and Software Architecture Exam Project"
  version: "1.0.0"

servers:
  - url: /v1 

tags:
 - name: "login"
 - name: "user"

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

paths:
  /v1/session:
    post:
      tags:
        - "login"
        - "user"
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: 'Ë†.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    # change here if you decide to use an integer
                    # or any other type of identifier
                    type: string
                    example: "abcdef012345"

  /v1/set_my_user_name:
    put:
      summary: Set user's username
      operationId: setMyUserName
      tags:
        - "user"
      responses:
        '200':
          description: User username updated successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/upload_photo:
    post:
      summary: Upload a photo
      operationId: uploadPhoto
      tags:
        - "photo"
      responses:
        '201':
          description: Photo uploaded successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/follow_user:
    post:
      summary: Follow a user
      operationId: followUser
      tags:
        - "user"
      responses:
        '201':
          description: User followed successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/unfollow_user:
    post:
      summary: Unfollow a user
      operationId: unfollowUser
      tags:
        - "user"
      responses:
        '201':
          description: User unfollowed successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/ban_user:
    post:
      summary: Ban a user
      operationId: banUser
      tags:
        - "user"
      responses:
        '201':
          description: User banned successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/unban_user:
    post:
      summary: Unban a user
      operationId: unbanUser
      tags:
        - "user"
      responses:
        '201':
          description: User unbanned successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/get_user_profile:
    get:
      summary: Get user profile
      operationId: getUserProfile
      tags:
        - "user"
      responses:
        '200':
          description: User profile retrieved successfully
        '404':
          description: User not found
      # Add necessary parameters and request/response details

  /v1/get_my_stream:
    get:
      summary: Get user's photo stream
      operationId: getMyStream
      tags:
        - "photo"
      responses:
        '200':
          description: User stream retrieved successfully
        '404':
          description: User not found
      # Add necessary parameters and request/response details

  /v1/like_photo:
    post:
      summary: Like a photo
      operationId: likePhoto
      tags:
        - "photo"
      responses:
        '201':
          description: Photo liked successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/unlike_photo:
    post:
      summary: Unlike a photo
      operationId: unlikePhoto
      tags:
        - "photo"
      responses:
        '201':
          description: Photo unliked successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/comment_photo:
    post:
      summary: Comment on a photo
      operationId: commentPhoto
      tags:
        - "photo"
      responses:
        '201':
          description: Photo commented successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/uncomment_photo:
    delete:
      summary: Remove a comment from a photo
      operationId: uncommentPhoto
      tags:
        - "photo"
      responses:
        '201':
          description: Comment removed successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details

  /v1/delete_photo:
    delete:
      summary: Delete a photo
      operationId: deletePhoto
      tags:
        - "photo"
      responses:
        '201':
          description: Photo deleted successfully
        '400':
          description: Bad request
      # Add necessary parameters and request/response details
